# Generated by Django 4.2 on 2025-11-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_invoice_cash_received_invoice_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
